ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
#from django.conf import settings
app_name="cart"
#from django.conf.urls.static import static

urlpatterns = [

    path('addtocart/<n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('full_remove/<n>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

#if settings.DEBUG:
 #  urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views
from django.conf import settings
app_name="search"
from django.conf.urls.static import static

urlpatterns = [

    path('',views.search,name="search"),

]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

from django.conf import settings

from django.conf.urls.static import static
app_name="shop"

urlpatterns = [

    path('',views.allcategories,name="allcat"),
    path('allprod/<p>',views.allproducts,name="allprod"),
    path('details/<c>',views.details,name="details"),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout', views.user_logout, name="logout"),

]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import product
from django.contrib.auth.models import User
from django.http import HttpResponse

class Cart(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
       # return self.user.name
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class order(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone = models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
      # return self.user.username
        return self.product.name

class account(models.Model):
    acctnum=models.IntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()

    def __str__(self):
        return str(self.acctnum)

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import product
from cart.models import Cart,order,account
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def cartview(request):
   total=0
   u=request.user
   try:
       cart=Cart.objects.filter(user=u)
       for i in cart:
          total+=i.quantity*i.product.price
   except:
      pass
   return render(request, 'cartview.html',{'c':cart ,'total':total})
@login_required
def addtocart(request,n):
    #return render(request, 'cartview.html')
    p=product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.product.stock > 0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()

    except:
        if(p.stock > 0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()

    return cartview(request)
@login_required
def cart_remove(request,n):
    p = product.objects.get(name=n)
    u = request.user
    try:
        cart=Cart.objects.get(user=u, product=p)
        if(cart.quantity>1):
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()

    except:
        pass
    return cartview(request)
@login_required
def full_remove(request,n):
    p = product.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()

    except:
        pass
    return cartview(request)

@login_required
def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)

   # return render(request,'orderform.html')
        total=0
        for i in cart:
            total += i.quantity*i.product.price

        try:
            num = int(n)
            ac = account.objects.get(num)

            if (ac.amount >= total):
                ac.amount = ac.amount - total
                ac.save()
                for i in cart:
                    o = order.objects.create(user=u, product=i.product, address=a,phone=p, no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg = "your order placed successfully"
                return render(request, 'orderdetail.html', {'msg': msg})
               # return HttpResponse("ordered")

            else:
               # return HttpResponse("insufficient")
                msg = "insufficient Amount.You can't place Order"
                return render(request, 'orderdetail.html', {'msg': msg})

        except:
            pass
    return render(request, 'orderform.html')
@login_required
def orderview(request):
    u=request.user
    o=order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import Q
# Create your views here.
def search(request):
    query=""
    products = None
    if (request.method=="POST"):
        query=request.POST['q']
        if query:
           products=product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request,'search.html', {'query': query, 'p': products})

ecommerce/templates/base.html
<!DOCTYPE html>
hello world
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
<header><center>
    <img src="{% static 'images/logo1.png' %}" class="mb-2" height="100px" width="100px"></center>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:lightgray">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link "  href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

             {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>

            {% if user.is_authenticated %}


             <li class="nav-item">
             <a class="nav-link "  href="{% url 'shop:logout' %}">Logout</a>
            </li>

          {% if user.is_superuser == True %}

          <li class="nav-item">
             <a class="nav-link"  href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sup class="mb-2">{{count}}</sup></i></a>
          </li>

          <li class="nav-item">
             <a class="nav-link"  href="{% url 'cart:orderview' %}">Your Orders</a>
          </li>
           {% endif %}




           {% else %}
          <li class="nav-item">
             <a class="nav-link "  href="{% url 'shop:register' %}">Register</a>
          </li>
          <li class="nav-item">
             <a class="nav-link "  href="{% url 'shop:login' %}">Login</a>
          </li>
          {% endif %}

      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

</header>


<!--h1>welcome to mypage</h1-->

<footer>
    <div class="footer">
        <p><b><i class="fa-solid fa-copyright"></i>Myshop Pvt Ltd.All Rights Reserved</b></p>
    </div>
</footer>

</body>
</html>
{% block content %}
{% endblock %}

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row fs-5 text-center">
    <h4 class="text-center">Shopping Cart</h4>
    <div class="col-7"><table class="table table-bordered">
      <tr><th colspan="5">Cart Items</th></tr>
  {% for i in c %}
    <tr><td>
        <img src="{{i.product.image.url}}" height="150px" width="150px">
    </td>
      <td><h6>{{i.product.name}}</h6></td>
      <td><h6>Product Id:{{i.product.id}}</h6>
        <h6>Unit Price:{{i.product.price}}</h6>
        <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6></td>
      <td>Subtotal:{{i.subtotal}}</td>
    <td>
      {% if i.product.stock > 0 %}

        <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-secondary fs-5"></i></a>
        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-info text-secondary fs-5"></i></a>
      {% else %}
        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-info text-secondary fs-5"></i></a></tr>
      {% endif %}</td>
  {% endfor %}

    </table></div>

    <div class="col-4 ms-3 fs-5" style="position:relative;">
      <table class="table table-bordered">
      <tr><th colspan="5">Check Out</th></tr>

      <tr><td>TOTAL:{{total}}</td></tr>
      </table>

    <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute;left:10px;">Place Order</a>
      <a href="{% url 'shop:allcat' %}" class="btn btn-danger" style="position:absolute;right:10px;">Continue Shopping</a>

    </div>

  </div>

</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'images/banner1.png' %}" height="350px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">Our collections</h3>
    <p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    </p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4 d-flex">

            <div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" >
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>

    <a href="{% url 'shop:allprod' i.name %}" class="btn btn-primary" style="position:relative;left:40%;" >Products</a>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container ">
<div class="row mt-5">
    <div class="col-sm-4 me-5">
      <img src="{{p.image.url}}" height="300px" width="340px">
    </div>
    <div class="col-sm-6 me-4">
        <h2>{{p.name}}</h2>
        <p class="mt-2 h6 lh-base" style="text-align:justify">{{p.desc}}</p>
        <h2 class="mt-2">{{p.price}}</h2>
{{p.stock}}
        {% if user.is_superuser == True %}
          {% if p.stock == 0 %}

          <h2>Out Of Stock</h2>
                <a href="{% url 'admin:index' %}" class="btn btn-danger mt-2">ADD STOCK</a>
          {% else %}
          <h2>Product in Stock</h2>
                <a href="{% url 'admin:index' %}" class="btn btn-danger mt-2">ADD STOCK</a>
          {% endif %}

        {% else %}

          {% if p.stock == 0 %}
          <h2>Out Of Stock</h2>
          {% else %}
        <a href="{% url 'cart:addtocart' p.name %}" class="btn btn-danger mt-2">ADD TO CART</a>
          {% endif %}
        {% endif %}

    </div>
</div>
</div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
   <h2>Login</h2>


<form method="POST">
    {% csrf_token %}
      <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" placeholder="Enter the username" name="u">
  </div>

      <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="p" placeholder="Enter the password" >
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

</center>


{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>

    <h4 class="text-center text-success">{{msg}}</h4>
    <h4 class="text-center text-danger">Thank you...</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h4>



</div>

{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>

    <div class="container">
         <h3>Order Form</h3>

        <form method="POST">
            {% csrf_token %}
          <div class="mb-3">
            <label  class="form-label">Address</label>
            <input type="text" class="form-control" name="a" placeholder="Enter the address" >
          </div>

          <div class="mb-3">
            <label  class="form-label">Phone</label>
            <input type="number" class="form-control" name="p" placeholder="Enter the phone number">
          </div>

          <div class="mb-3">
            <label  class="form-label">Account Number</label>
            <input type="number" class="form-control" name="n" placeholder="Enter the account number">
          </div>


          <button type="submit" class="btn btn-danger">Submit</button>
        </form>





    </div>
</center>


{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <div class="row mt-5">
    <h4 class=" text-danger">Name of the customer : {{u}}</h4>
    {% for i in o %}
    <div class="col-sm-4 mt-3" style="margin-left:100px;" >
      <img src="{{i.product.image.url}}" height="150px" width="150px">
    </div>
    <div class="col-sm-6 text-center mt-3">
        <b>Product name : {{i.product.name}}</b><br>
        <b>Product price : {{i.product.price}}</b><br>
        <b>Delivery_address : {{i.address}}</b><br>
        <b>Customer Phone : {{i.phone}}</b><br>
        <b>Ordered on : {{i.ordered_date}}</b><br>
        <b class="text-success">Delivery_status : {{i.delivery.status}}</b><br>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="350px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify;line-height:2;">{{c.desc}}</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4 d-flex">

            <div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" >
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
        <h5 class="card-title text-center">{{i.price}}</h5>

    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Details</a>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <div class="container" style="margin-bottom:100px">
   <h2>Register</h2>

<form method="POST">
    {% csrf_token %}
      <div class="mb-3">
    <label  class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter the username" >
  </div>

      <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control"  name="p" placeholder="Enter the password" >
  </div>

      <div class="mb-3">
    <label  class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp"  placeholder="Enter the confirm password">
  </div>


  <div class="mb-3">
    <label  class="form-label">Email address</label>
    <input type="email" class="form-control"  aria-describedby="emailHelp" name="e" placeholder="Enter the email address">

  </div>
       <div class="mb-3">
    <label  class="form-label">First name</label>
    <input type="text" class="form-control" name="f" placeholder="Enter the firstname" >
  </div>
      <div class="mb-3">
    <label  class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="Enter the lastname">
  </div>

  <button type="submit" class=" btn btn-secondary">Submit</button>
</form></div>

</center>


{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
    <div>
       <h3>You have searched for {{query}}</h3>
    </div>
</center>


<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="text-align:justify;line-height:2;">{{c.desc}}</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        <!--{% if p %}-->
        {% for i in p %}
        <div class="col-sm-4 mb-5 d-flex">

            <div class="card" style="width:30rem;">
  <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" >
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
        <h5 class="card-title text-center">{{i.price}}</h5>

    <a href="{% url 'shop:details' i.name %}" class="btn btn-primary" style="position:relative;left:40%;">Details</a>
  </div>
</div>

        </div>
        {% endfor %}

        {% else %}
        <h4 class="text-center">No Results Found</h4>
        {% endif %}
    </div>
</div>


{% endblock %}